theme: jekyll-theme-minimal
title: pyrecraft
description: making something different

github:
  is_project_page: false

logo: ./mined-mind-logo.gif
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
